export const Bin = (size,color)=>{return<img src="https://i.ibb.co/5WgsmK7/bin.png" alt="bin" width={size ? size.size[0]:""} height={size ? size.size[1]:""} color={color ? color : ""}></img>}
export const Check = (size,color)=>{return<img src="https://i.ibb.co/gTFF2sK/check.png" alt="bin" width={size ? size.size[0]:""} height={size ? size.size[1]:""} color={color ? color : ""}></img>}
export const Downarrow = (size,color)=>{return<img src="https://i.ibb.co/yVLbfCP/down-arrow.png" width={size ? size.size[0]:""} height={size ? size.size[1]:""} color={color ? color : ""}></img>}
export const Editer = (size,color)=>{return<img src="https://i.ibb.co/q0knFXT/editer.png" alt="bin" width={size ? size.size[0]:""} height={size ? size.size[1]:""} color={color ? color : ""}></img>}
export const Link = (size,color)=>{return<img src="https://i.ibb.co/LQ5nKJn/external-link.png" alt="bin" width={size ? size.size[0]:""} height={size ? size.size[1]:""} color={color ? color : ""}></img>}
export const Group = (size,color)=>{return<img src="https://i.ibb.co/DwtZTw7/group.png" alt="bin" width={size ? size.size[0]:""} height={size ? size.size[1]:""} color={color ? color : ""}></img>}
export const Home = (size,color)=>{return<img src="https://i.ibb.co/WtB2jk0/home.png" alt="bin" width={size ? size.size[0]:""} height={size ? size.size[1]:""} color={color ? color : ""}></img>}
export const Project = (size,color)=>{return<img src="https://i.ibb.co/Yb8rkb0/project.png" alt="bin" width={size ? size.size[0]:""} height={size ? size.size[1]:""} color={color ? color : ""}></img>}
export const Rabbit = ()=>{return<img src="https://i.ibb.co/nwxx7VQ/rabbit.jpg" className="w-full h-screen" alt="bin"></img>}
export const Timer = (size,color)=>{return<img src="https://i.ibb.co/7NNDr95/timer.png" alt="bin" width={size ? size.size[0]:""} height={size ? size.size[1]:""} color={color ? color : ""}></img>}
export const View = (size,color)=>{return<img src="https://i.ibb.co/4Ybz0Z7/view.png" alt="bin" width={size ? size.size[0]:""} height={size ? size.size[1]:""} color={color ? color : ""}></img>}